### ISSUE TITLE
Error when running test samples

### ISSUE THREAD

**Issue by pryratess** [ozagordi/LocalVariants#2]
Hello, 

I'm having troubles running the localvariants program with both my samples and tests and every time I try I get this error. Can't figure out a solution.

Traceback (most recent call last):
  File "/usr/local/bin/localvar", line 26, in <module>
    mod = **import**('localvariants')
ImportError: No module named 'localvariants'

Thanks!

**Comment by ozagordi** [comment]
Hi. Sorry for the late reply, error in the notification setting. Can you please tell me how you run it?
