### ISSUE TITLE
Error with my data

### ISSUE THREAD

**Issue by saminhf** [ozagordi/LocalVariants#3]
Hi,
I am using this program to detect the number of haplotypes per a 4000nt gene which is related to a plant virus but I got this error:
 File "LStructure.py", line 29
    print('Downloading HIV reference from PubMed', file=sys.stderr)
    SyntaxError: invalid syntax

Could you please guide me?
Thanks

**Comment by ozagordi** [comment]
Do you have python3? Please update and try to rerun. I now made the python3.4 call explicit.
